### PR TITLE
add traefik 2 configuration

### PR DESCRIPTION
**Pull request by avarabyeu**
#744 
Migrate to Traefik v2

### CODE REVIEW

**Comment by DzmitryHumianiuk** [comment]
this should be tested carefully before merge into default docs

**Comment by pbortnik** [comment]
Need to refactor service-index according to new traefik api

**Comment by DzmitryHumianiuk** [comment]
@pbortnik then it should be 5.1

**Comment by pbortnik** [comment]
Should be merged after 5.1 released

**Comment by pbortnik** [comment]
Merged remotely

**Pull request closed without merging**
